name: Bumping

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Bump type"
        required: false
        type: choice
        options:
        - patch
        - minor
  pull_request:
    branches: [staging]
    types: [closed]

jobs:
  with-workflow:
    uses: n0bra1n3r/github-workflows/.github/workflows/bump_version.yml@staging
    secrets:
      ACCESS_TOKEN: ${{ secrets.MASTER_PAT }}
      GIT_AUTHOR_NAME: ${{ secrets.DEFAULT_GIT_AUTHOR_NAME }}
      GIT_AUTHOR_EMAIL: ${{ secrets.DEFAULT_GIT_AUTHOR_EMAIL }}
      GIT_COMMITTER_NAME: ${{ secrets.DEFAULT_GIT_AUTHOR_NAME }}
      GIT_COMMITTER_EMAIL: ${{ secrets.DEFAULT_GIT_AUTHOR_EMAIL }}
