name: Bumping

on:
  pull_request:
    branches: [staging]
    types: [closed]

concurrency:
  group: bumping
  cancel-in-progress: true

env:
  GIT_AUTHOR_NAME: ${{ secrets.DEFAULT_GIT_AUTHOR_NAME }}
  GIT_AUTHOR_EMAIL: ${{ secrets.DEFAULT_GIT_AUTHOR_EMAIL }}
  GIT_COMMITTER_NAME: ${{ secrets.DEFAULT_GIT_AUTHOR_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.DEFAULT_GIT_AUTHOR_EMAIL }}

jobs:
  version_patch:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'bump patch')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump version patch
      run: |
        GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        GIT_TAG_BUMPED=$(perl -pe 's/^(\d+\.)(\d+\.)(\d+)$/$1.$2.($3+1)/e' <<<"$GIT_TAG")
        sed -i "s/^\(version *= *\)\"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\1\"$GIT_TAG_BUMPED\"/g" cinterop.nimble
        git commit -am "Bump version"
        git tag $GIT_TAG_BUMPED
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
  version_minor:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'bump minor')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump version minor
      run: |
        GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        GIT_TAG_BUMPED=$(perl -pe 's/^(\d+\.)(\d+)(\.\d+)$/$1.($2+1).$3/e' <<<"$GIT_TAG")
        sed -i "s/^\(version *= *\)\"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\1\"$GIT_TAG_BUMPED\"/g" cinterop.nimble
        git commit -am "Bump version"
        git tag $GIT_TAG_BUMPED
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
